name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk libffi-dev libssl-dev libjpeg-dev libpng-dev

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Accept Android SDK licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true

      - name: Initialize Buildozer if missing
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: |
          export BUILDOZER_ACCEPT_LICENSE=1
          buildozer --verbose android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: study-planner-apk
          path: bin/*.apk
